keys:
  # SRE
  - &sre age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m

  # Misc
  - &misc1-metadata-a-1 age187hd0pffv549vfcmnw5u9yg3fck9e4psesz2xchrklqjqepccd7s6vlkcv

  # Preprod
  - &preprod1-bp-a-1 age1zhewzr3r8u4qmu9c5asw0vv9pw9qxvah9y60reu5uggrr8vrd95skhn3q3
  - &preprod1-faucet-a-1 age13mcml2m95r7rm7qmgd8vmpv3afce2ckyk0szgter6c3st75gf5cs4j6dq5
  - &preprod2-bp-b-1 age1mcvj04swen8l0yjgkpng3rpzdk0xycg52h2g2ktflhw3szvg83rqcvdawg
  - &preprod3-bp-c-1 age18c8cwh94uyvt0a65pashccsp7falmqhdhp4p9paug2v3af9etfwsq67ds6

  # Preview
  - &preview1-bp-a-1 age10mgec0e4xp87x79fsd5r9pdggt8gr4mjpnj98zhlpvzx6almhd5sxrakyh
  - &preview1-faucet-a-1 age1mcyrt3d2d092gall6s8rm5drcffaawh29ssuqszzzeempsezxs3qh2n2uk
  - &preview2-bp-b-1 age1jcfeznfkxx2rmeej9f4frvnjqkxdpd9kg56l57nmtamq53802fjq7x2y69
  - &preview3-bp-c-1 age13tc9mjgu7hwfxsa84hq0tcz7eeg9m6f0fmg8gzxwme30pfxf7g4sfk2y0k

  # Private
  - &private1-bp-a-1 age1pwmcf9nez82glwzk3mfcfyv0wnc4yev8pjhxk43fwgcr3m8yjsesjdfha0
  - &private1-dbsync-a-1 age1q435aw99zpavtn5ce770jesh3th0ghne8jkt5mse8zscpp5r2ghsark64e
  - &private1-faucet-a-1 age1lack6chc6czx8t9sc9ayc3wq0du82ne6l8m5h6lwz8zn6rxz5gqqtpz4z2
  - &private2-bp-b-1 age1wewhhymvzljpgy7v9caud2zmgjt7dsdcluvpq8373ueuj5qv435qgn9xae
  - &private3-bp-c-1 age1ay9e566ksavc46809vzjzcwlsu06dzr869fdv8qf9p9qu69qva4ssdv4af

  # Sanchonet
  - &sanchonet1-bp-a-1 age1apa4g9hfjaq9kp95utg5jeqm9zmdhylcfsqmekrl0ptg4wjt53fsrfffy9
  - &sanchonet1-dbsync-a-1 age1d5nc5w5th0qzagqa8xqltye2ttsuazury35pgwymyrnzrdk6zezqznv0ua
  - &sanchonet1-faucet-a-1 age15cj5hg52ep6ccc4t5xm9ncuf94m2ds4k02lzzvmeykx2z4gc83es5ze452
  - &sanchonet2-bp-b-1 age10ethn6sqe2fcx03pev0vddteg9jwe7azydq9glj9eyppdkqy855sxv40k9
  - &sanchonet3-bp-c-1 age1hpyzunphtls4tfk5j4dc4rxg55essxd3ht7fweapumfzqe8h5suq0xa699

  # Shelley-qa
  - &shelley-qa1-bp-a-1 age1xxu6w2sftwxp5aef9yes20wegwv62pwhg7jzvt60q4ucwl6eyfaskjgqfu
  - &shelley-qa1-faucet-a-1 age1pcg2a9pzfcl6jwkzchyhlg30nznfaaecjwnpy2am6mhq8kvgf9msudxt5a
  - &shelley-qa2-bp-b-1 age1pzcdrzm9j4pxar6nx9wu7le95apw7gu4838s22u7evycydcunu3qw7eafy
  - &shelley-qa3-bp-c-1 age19ulgvpe2wnvmu6tujae0ekn2stz46ntw0n03et4ctjk8nawa25eq6luw8f

  # Mainnet, non-prod testing machines
  - &mainnet1-rel-a-1 age16m0sd0pyme79ds8jd380ctuc23p570djl0rnrp6xt28tce5ltvyql4hdgn

creation_rules:
  # -------------------------------------------------------
  # General environment secrets are admin only
  - path_regex: (secrets|workbench)/envs/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group no-deploy secrets are admin only
  - path_regex: (secrets|workbench)/groups/[^/]+/no-deploy/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group producer and other secrets
  # Preprod specific
  - path_regex: secrets/groups/preprod1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-faucet-a-1

  - path_regex: secrets/groups/preprod1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-bp-a-1

  - path_regex: secrets/groups/preprod2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod2-bp-b-1

  - path_regex: secrets/groups/preprod3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod3-bp-c-1

  # Preview specific
  - path_regex: secrets/groups/preview1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *preview1-faucet-a-1

  - path_regex: secrets/groups/preview1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview1-bp-a-1

  - path_regex: secrets/groups/preview2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview2-bp-b-1

  - path_regex: secrets/groups/preview3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview3-bp-c-1

  # Private specific
  - path_regex: secrets/groups/private1/deploy/.*govtool-backend.*$
    key_groups:
    - age:
      - *sre
      - *private1-dbsync-a-1

  - path_regex: secrets/groups/private1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *private1-faucet-a-1

  - path_regex: secrets/groups/private1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *private1-bp-a-1

  - path_regex: secrets/groups/private2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *private2-bp-b-1

  - path_regex: secrets/groups/private3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *private3-bp-c-1

  # Sanchonet specific
  - path_regex: secrets/groups/sanchonet1/deploy/.*govtool-backend.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet1-dbsync-a-1

  - path_regex: secrets/groups/sanchonet1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet1-faucet-a-1

  - path_regex: secrets/groups/sanchonet1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet1-bp-a-1

  - path_regex: secrets/groups/sanchonet2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet2-bp-b-1

  - path_regex: secrets/groups/sanchonet3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet3-bp-c-1

  # Shelley-qa specific
  - path_regex: secrets/groups/shelley-qa1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *shelley-qa1-faucet-a-1

  - path_regex: secrets/groups/shelley-qa1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *shelley-qa1-bp-a-1

  - path_regex: secrets/groups/shelley-qa2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *shelley-qa2-bp-b-1

  - path_regex: secrets/groups/shelley-qa3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *shelley-qa3-bp-c-1

  # Mainnet non-prod specific
  - path_regex: secrets/groups/mainnet1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *mainnet1-rel-a-1

  # Miscellaneous group specific
  - path_regex: secrets/groups/misc1/deploy/.*metadata.*$
    key_groups:
    - age:
      - *sre
      - *misc1-metadata-a-1

  # -------------------------------------------------------
  # Workbench pool onboarding -- modify during creation
  # Modify and add specific block producer keys as needed
  - path_regex: workbench/groups/deploy/[^/]+/.*$
    key_groups:
    - age:
      - *sre
  #   - *EXAMPLE_MACHINE_KEY

  # -------------------------------------------------------
  # Secrets and workbench catch all
  - path_regex: (secrets|workbench)/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # State-demo functionality test
  - path_regex: state-demo/(envs|groups)/.*$
    key_groups:
    - age:
      - *sre
