keys:
  # SRE
  - &sre age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m

  # AI
  - &ai age18t54l645q8p8s5m2l5hs7pck9rfvv0pfzlppec6f6aj3j8zh5e6qwcea47

  # Misc
  - &misc1-metadata-a-1 age187hd0pffv549vfcmnw5u9yg3fck9e4psesz2xchrklqjqepccd7s6vlkcv
  - &misc1-wg-a-1 age1ryvlcaajedpnkdyugnre6yysht5ahkn3yrwz48wvywpn2sxwfqtqrc8qmn
  - &misc1-wg-b-1 age1tsyap098spn8j6nshvc56y4cucfuxr53wcapdy39lxqm8qfuvf7qd60m06

  # Preprod
  - &preprod1-bp-a-1 age1zhewzr3r8u4qmu9c5asw0vv9pw9qxvah9y60reu5uggrr8vrd95skhn3q3
  - &preprod1-faucet-a-1 age13mcml2m95r7rm7qmgd8vmpv3afce2ckyk0szgter6c3st75gf5cs4j6dq5
  - &preprod2-bp-b-1 age1mcvj04swen8l0yjgkpng3rpzdk0xycg52h2g2ktflhw3szvg83rqcvdawg
  - &preprod3-bp-c-1 age18c8cwh94uyvt0a65pashccsp7falmqhdhp4p9paug2v3af9etfwsq67ds6

  # Preview
  - &preview1-bp-a-1 age10mgec0e4xp87x79fsd5r9pdggt8gr4mjpnj98zhlpvzx6almhd5sxrakyh
  - &preview1-faucet-a-1 age1mcyrt3d2d092gall6s8rm5drcffaawh29ssuqszzzeempsezxs3qh2n2uk
  - &preview1-test-a-1 age1fsgltv09d4mdvzdkhsqufj8f4h7k8k7jfmps4n9stwalpdzf6fss6spdv0
  - &preview2-bp-b-1 age1jcfeznfkxx2rmeej9f4frvnjqkxdpd9kg56l57nmtamq53802fjq7x2y69
  - &preview3-bp-c-1 age13tc9mjgu7hwfxsa84hq0tcz7eeg9m6f0fmg8gzxwme30pfxf7g4sfk2y0k

  # Dijkstra
  - &dijkstra1-bp-a-1 age18jtrsvmgdsz7007yttj0elmwaq890dz228jhl3a5hpg5fenzxf2sap2wcz
  - &dijkstra1-faucet-a-1 age1fmqm27fdwldfmsuq2xy2qtgl5tzameuzxn29s2ka9e4063lsdcls4ezlgk
  - &dijkstra2-bp-b-1 age18effywervp368ygfyxsywvcs89nnkrs7lm3s3z09kzcy758n29astfnrpx
  - &dijkstra3-bp-c-1 age1aflfe3ufz6vun3kwxy4ht83g8thu30dsmzpv3va6epeqcnffkfzqzeapgy

  # Leios
  - &leios1-bp-a-1 age154hm2nsnpv794q6md6k96gx8r422v2gu74wuyzl4ehkg62ajldkst9lmc6
  - &leios1-faucet-a-1 age1dwepnrvk2ysjkh5uqj7sshyp20yck5kjpvlzfra6rh2rj9ps8eeqzjgw4c
  - &leios1-centrifuge-a-1 age1wavssdycw4cumqtws84a57c5r8u6366kw5e7ctjcqgkdzrsfyy2q6rtllk
  - &leios1-metsuke-a-1 age137wf2507wl07lm9qnl8rszuhf5ltjfa6x8xz3a5tnjcceqsgrdpqlve8yc
  - &leios2-bp-b-1 age1lt8a78g53sgpspgtnce3w5v2fswdhhr7cnkl3eg4gkepd7gdd9lqcpy95c
  - &leios3-bp-c-1 age1pn8tx5ehm7hejphk6ewlvlmpmg4ujq4gc92mtudhsqpapj3q4apscyjwcy
  - &leiosred1-bp-a-1 age1x9rklez6g95grqhgm5rlfyu3nt2gmtptnmh3c0uu9nw46r22mchqhj54fk
  - &leiosred2-bp-b-1 age1ew7xmm6ypqtn6c8jl9chrctk3ghgju2zfgnvy8kjm46eyzs5vvusr4emcu
  - &leiosred3-bp-c-1 age100j4usae4uwn89vh6x336d94vw8n2x7qcqmpjgdra20f7kzztyeqwa66t9
  - &leiosred4-bp-d-1 age12qc4alfpep36dmflvry7lj8gx83j0llgckjq855smaf79e765eesd2mjhx
  - &leiosred5-bp-e-1 age1zst0d69z6y4u960fg2q3rpw5jsl3mfnln7k9lm8tlud4dcn5tudq9uj4hy
  - &leiosred6-bp-f-1 age1uhr0ywvd70eq09rcgmgn2n59jqfqafwjkuccc23wemnawj0zqacsaadtgu
  - &leiosred7-bp-g-1 age15vkvs9mp5c3wws9m08xvfyw7j985aw846xy20r8ukj8pxmarguwqeccmqy
  - &leiosred8-bp-h-1 age1c9eslsymressueqr9c77er87uewjqdl40fjpgu0t7apuhccg7fes2txaje
  - &leiosred9-bp-i-1 age1dxg5nq4u3hdpsg8pzpaeh40p7muj4r9hfw5sjd6efcnlj2dqz3zqcfhplw
  - &leiosred10-bp-j-1 age1eyvhtuftwvwhc7spapukdhpagjd7hvp4xvex3kq9cdup23nn9g9q5nz64p

  # Sanchonet
  - &sanchonet1-bp-a-1 age1sxhjqwnuf5duczjv5fwle492jpm7fhwunkwhp6agle6y75yqdeas586aaj

  # Mainnet, non-prod testing machines
  - &mainnet1-rel-a-1 age16m0sd0pyme79ds8jd380ctuc23p570djl0rnrp6xt28tce5ltvyql4hdgn

  # Buildkite
  - &buildkite1-ap-southeast-2-1 age1q4nfkghxujn8xfxrwaazvjjunfjnrnt4wfzx57zas6cvkde3m4tscfutt9
  - &buildkite1-eu-central-1-1 age1lsn2rs6gd0yeyq7dr25xmmxa3mh5fefgy5rttlfqzd66n37qgfmsyx3lsu
  - &buildkite1-sa-east-1-1 age1f8ljwl7pauzfqpqjnxvz9cp0ln4ptldvjlyp3p6882klcrtswp5s30qkz7
  - &buildkite-af-south-1-1 age1mznysjmhug030jh7sgvp4tueurzwzvvl07cpnx9lp5n25xvmdfgspyjzpv

creation_rules:
  # -------------------------------------------------------
  # General environment secrets are admin only
  - path_regex: (secrets|workbench)/envs/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group no-deploy secrets are admin only
  - path_regex: (secrets|workbench)/groups/[^/]+/no-deploy/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # AI secrets
  - path_regex: secrets/ai/.*$
    key_groups:
    - age:
      - *sre
      - *ai

  # -------------------------------------------------------
  # Group producer and other secrets
  # Preprod specific
  - path_regex: secrets/groups/preprod1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-faucet-a-1

  - path_regex: secrets/groups/preprod1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-bp-a-1

  - path_regex: secrets/groups/preprod2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod2-bp-b-1

  - path_regex: secrets/groups/preprod3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod3-bp-c-1

  # Preview specific
  - path_regex: secrets/groups/preview1/deploy/preview1-bp-a-1.*$
    key_groups:
    - age:
      - *sre
      - *preview1-bp-a-1

  - path_regex: secrets/groups/preview1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *preview1-faucet-a-1

  - path_regex: secrets/groups/preview1/deploy/preview1-test-a-1.*$
    key_groups:
    - age:
      - *sre
      - *preview1-test-a-1

  - path_regex: secrets/groups/preview2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview2-bp-b-1

  - path_regex: secrets/groups/preview3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview3-bp-c-1

  # Dijkstra specific
  - path_regex: secrets/groups/dijkstra1/deploy/dijkstra1-bp-a-1.*$
    key_groups:
    - age:
      - *sre
      - *dijkstra1-bp-a-1

  - path_regex: secrets/groups/dijkstra1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *dijkstra1-faucet-a-1

  - path_regex: secrets/groups/dijkstra2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *dijkstra2-bp-b-1

  - path_regex: secrets/groups/dijkstra3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *dijkstra3-bp-c-1

  # Leios specific
  - path_regex: secrets/groups/leios1/deploy/leios1-bp-a-1.*$
    key_groups:
    - age:
      - *sre
      - *leios1-bp-a-1

  - path_regex: secrets/groups/leios1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *leios1-faucet-a-1

  - path_regex: secrets/groups/leios1/deploy/.*metsuke.*$
    key_groups:
    - age:
      - *sre
      - *leios1-metsuke-a-1

  - path_regex: secrets/groups/leios1/deploy/leios1-centrifuge-a-1.*$
    key_groups:
    - age:
      - *sre
      - *leios1-centrifuge-a-1

  - path_regex: secrets/groups/leios2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *leios2-bp-b-1

  - path_regex: secrets/groups/leios3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *leios3-bp-c-1

  - path_regex: secrets/groups/leiosred1/deploy/leiosred1-bp-a-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred1-bp-a-1

  - path_regex: secrets/groups/leiosred2/deploy/leiosred2-bp-b-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred2-bp-b-1

  - path_regex: secrets/groups/leiosred3/deploy/leiosred3-bp-c-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred3-bp-c-1

  - path_regex: secrets/groups/leiosred4/deploy/leiosred4-bp-d-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred4-bp-d-1

  - path_regex: secrets/groups/leiosred5/deploy/leiosred5-bp-e-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred5-bp-e-1

  - path_regex: secrets/groups/leiosred6/deploy/leiosred6-bp-f-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred6-bp-f-1

  - path_regex: secrets/groups/leiosred7/deploy/leiosred7-bp-g-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred7-bp-g-1

  - path_regex: secrets/groups/leiosred8/deploy/leiosred8-bp-h-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred8-bp-h-1

  - path_regex: secrets/groups/leiosred9/deploy/leiosred9-bp-i-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred9-bp-i-1

  - path_regex: secrets/groups/leiosred10/deploy/leiosred10-bp-j-1.*$
    key_groups:
    - age:
      - *sre
      - *leiosred10-bp-j-1

  # Sanchonet specific
  - path_regex: secrets/groups/sanchonet1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet1-bp-a-1

  # Mainnet non-prod specific
  - path_regex: secrets/groups/mainnet1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *mainnet1-rel-a-1

  # Miscellaneous group specific, metadata server
  - path_regex: secrets/groups/misc1/deploy/.*metadata.*$
    key_groups:
    - age:
      - *sre
      - *misc1-metadata-a-1

  # Miscellaneous group specific, wireguard tunnel
  - path_regex: secrets/groups/misc1/deploy/.*wg-a-1.*$
    key_groups:
    - age:
      - *sre
      - *misc1-wg-a-1

  # Miscellaneous group specific, wireguard tunnel arn
  - path_regex: secrets/groups/misc1/deploy/.*wg-b-1.*$
    key_groups:
    - age:
      - *sre
      - *misc1-wg-b-1

  # Temporary buildkite testing
  - path_regex: secrets/buildkite/.*$
    key_groups:
    - age:
      - *sre
      - *buildkite1-ap-southeast-2-1
      - *buildkite1-eu-central-1-1
      - *buildkite1-sa-east-1-1
      - *buildkite-af-south-1-1

  # Nix config file that sets access-tokens
  - path_regex: secrets/nix-access-tokens.conf$
    key_groups:
    - age:
      - *sre
      - *leiosred1-bp-a-1
      - *leiosred2-bp-b-1
      - *leiosred3-bp-c-1
      - *leiosred4-bp-d-1
      - *leiosred5-bp-e-1
      - *leiosred6-bp-f-1
      - *leiosred7-bp-g-1
      - *leiosred8-bp-h-1
      - *leiosred9-bp-i-1
      - *leiosred10-bp-j-1

  # -------------------------------------------------------
  # Workbench pool onboarding -- modify during creation
  # Modify and add specific block producer keys as needed
  - path_regex: workbench/groups/deploy/[^/]+/.*$
    key_groups:
    - age:
      - *sre
  #   - *EXAMPLE_MACHINE_KEY

  # -------------------------------------------------------
  # Secrets and workbench catch all
  - path_regex: (secrets|workbench)/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # State-demo functionality test
  - path_regex: state-demo(-ng)?/(envs|groups)/.*$
    key_groups:
    - age:
      - *sre
