keys:
  # SRE
  - &sre age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m

  # Misc
  - &misc1-metadata-a-1 age187hd0pffv549vfcmnw5u9yg3fck9e4psesz2xchrklqjqepccd7s6vlkcv
  - &misc1-wg-a-1 age1ryvlcaajedpnkdyugnre6yysht5ahkn3yrwz48wvywpn2sxwfqtqrc8qmn

  # Preprod
  - &preprod1-bp-a-1 age1zhewzr3r8u4qmu9c5asw0vv9pw9qxvah9y60reu5uggrr8vrd95skhn3q3
  - &preprod1-faucet-a-1 age13mcml2m95r7rm7qmgd8vmpv3afce2ckyk0szgter6c3st75gf5cs4j6dq5
  - &preprod2-bp-b-1 age1mcvj04swen8l0yjgkpng3rpzdk0xycg52h2g2ktflhw3szvg83rqcvdawg
  - &preprod3-bp-c-1 age18c8cwh94uyvt0a65pashccsp7falmqhdhp4p9paug2v3af9etfwsq67ds6

  # Preview
  - &preview1-bp-a-1 age10mgec0e4xp87x79fsd5r9pdggt8gr4mjpnj98zhlpvzx6almhd5sxrakyh
  - &preview1-faucet-a-1 age1mcyrt3d2d092gall6s8rm5drcffaawh29ssuqszzzeempsezxs3qh2n2uk
  - &preview1-test-a-1 age1fsgltv09d4mdvzdkhsqufj8f4h7k8k7jfmps4n9stwalpdzf6fss6spdv0
  - &preview2-bp-b-1 age1jcfeznfkxx2rmeej9f4frvnjqkxdpd9kg56l57nmtamq53802fjq7x2y69
  - &preview3-bp-c-1 age13tc9mjgu7hwfxsa84hq0tcz7eeg9m6f0fmg8gzxwme30pfxf7g4sfk2y0k

  # Sanchonet
  - &sanchonet1-bp-a-1 age1sxhjqwnuf5duczjv5fwle492jpm7fhwunkwhp6agle6y75yqdeas586aaj

  # Mainnet, non-prod testing machines
  - &mainnet1-rel-a-1 age16m0sd0pyme79ds8jd380ctuc23p570djl0rnrp6xt28tce5ltvyql4hdgn

  # Buildkite
  - &buildkite1-ap-southeast-2-1 age1q4nfkghxujn8xfxrwaazvjjunfjnrnt4wfzx57zas6cvkde3m4tscfutt9
  - &buildkite1-eu-central-1-1 age1lsn2rs6gd0yeyq7dr25xmmxa3mh5fefgy5rttlfqzd66n37qgfmsyx3lsu
  - &buildkite1-sa-east-1-1 age1f8ljwl7pauzfqpqjnxvz9cp0ln4ptldvjlyp3p6882klcrtswp5s30qkz7
  - &buildkite-af-south-1-1 age1mznysjmhug030jh7sgvp4tueurzwzvvl07cpnx9lp5n25xvmdfgspyjzpv

creation_rules:
  # -------------------------------------------------------
  # General environment secrets are admin only
  - path_regex: (secrets|workbench)/envs/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group no-deploy secrets are admin only
  - path_regex: (secrets|workbench)/groups/[^/]+/no-deploy/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # Group producer and other secrets
  # Preprod specific
  - path_regex: secrets/groups/preprod1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-faucet-a-1

  - path_regex: secrets/groups/preprod1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-bp-a-1

  - path_regex: secrets/groups/preprod2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod2-bp-b-1

  - path_regex: secrets/groups/preprod3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preprod3-bp-c-1

  # Preview specific
  - path_regex: secrets/groups/preview1/deploy/preview1-bp-a-1.*$
    key_groups:
    - age:
      - *sre
      - *preview1-bp-a-1

  - path_regex: secrets/groups/preview1/deploy/.*faucet.*$
    key_groups:
    - age:
      - *sre
      - *preview1-faucet-a-1

  - path_regex: secrets/groups/preview1/deploy/preview1-test-a-1.*$
    key_groups:
    - age:
      - *sre
      - *preview1-test-a-1

  - path_regex: secrets/groups/preview2/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview2-bp-b-1

  - path_regex: secrets/groups/preview3/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *preview3-bp-c-1

  # Sanchonet specific
  - path_regex: secrets/groups/sanchonet1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet1-bp-a-1

  # Mainnet non-prod specific
  - path_regex: secrets/groups/mainnet1/deploy/.*$
    key_groups:
    - age:
      - *sre
      - *mainnet1-rel-a-1

  # Miscellaneous group specific, metadata server
  - path_regex: secrets/groups/misc1/deploy/.*metadata.*$
    key_groups:
    - age:
      - *sre
      - *misc1-metadata-a-1

  # Miscellaneous group specific, wireguard tunnel
  - path_regex: secrets/groups/misc1/deploy/.*wg.*$
    key_groups:
    - age:
      - *sre
      - *misc1-wg-a-1

  # Temporary buildkite testing
  - path_regex: secrets/buildkite/.*$
    key_groups:
    - age:
      - *sre
      - *buildkite1-ap-southeast-2-1
      - *buildkite1-eu-central-1-1
      - *buildkite1-sa-east-1-1
      - *buildkite-af-south-1-1

  # -------------------------------------------------------
  # Workbench pool onboarding -- modify during creation
  # Modify and add specific block producer keys as needed
  - path_regex: workbench/groups/deploy/[^/]+/.*$
    key_groups:
    - age:
      - *sre
  #   - *EXAMPLE_MACHINE_KEY

  # -------------------------------------------------------
  # Secrets and workbench catch all
  - path_regex: (secrets|workbench)/.*$
    key_groups:
    - age:
      - *sre

  # -------------------------------------------------------
  # State-demo functionality test
  - path_regex: state-demo(-ng)?/(envs|groups)/.*$
    key_groups:
    - age:
      - *sre
