---
apiVersion: argoproj.io/v1alpha1  # first, required
kind: Application  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app.kubernetes.io/name: TODO  # first, required
  annotations: {}
  finalizers: []
spec:  # required
  revisionHistoryLimit: TODO  # first
  project: TODO  # required
  source:  # required
    repoURL: TODO  # required
    targetRevision: TODO  # required
    path: TODO  # required
    kustomize:
      version: TODO
  destination:  # required
    name: TODO  # first
    server: TODO
  syncPolicy:  # required
    automated:  # preferred
      prune: TODO  # preferred
      selfHeal: TODO  # preferred
    syncOptions: []  # preferred
    retry:  # preferred
      limit: TODO  # preferred
      backoff:  # preferred
        duration: TODO  # preferred
        factor: TODO  # preferred
        maxDuration: TODO  # preferred
