---
apiVersion: security.istio.io/v1  # first, required
kind: AuthorizationPolicy  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app.kubernetes.io/name: TODO  # required
spec:  # required
  action: TODO  # first, required
  rules:  # required
  - from:
    - source:
        namespaces:
        - TODO
