---
apiVersion: v1  # first, required
kind: ConfigMap  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app.kubernetes.io/name: TODO  # required
  annotations: {}
immutable: false
data: {}  # required
