---
apiVersion: apps/v1  # first, required
kind: DaemonSet  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
spec:  # required
  selector:  # required
    matchLabels: {}  # required
  updateStrategy:  # preferred
    type: TODO  # first, required
  template:  # required
    metadata:  # required
      labels:  # required
        app: TODO  # first
        app.kubernetes.io/name: TODO  # required
    spec: {}  # ditto=Pod.spec
