---
apiVersion: gateway.networking.k8s.io/v1  # first, required
kind: HTTPRoute  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # required
  labels:  # required
    app.kubernetes.io/name: TODO  # required
spec:  # required
  parentRefs:  # first, required
  - name: TODO  # first, required
    namespace: TODO  # required
  hostnames: []  # required
  rules:  # required
  - matches:  # first, required
    - path:  # required
        type: TODO  # required
        value: TODO  # required
    backendRefs:  # required
    - name: TODO  # first, required
      port: TODO  # required
