---
apiVersion: gateway.networking.k8s.io/v1beta1  # first, required
kind: ReferenceGrant  # required
metadata:  # required
  name: TODO  # required
  namespace: TODO  # required
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
spec:  # required
  from:  # first, required
  - group: TODO  # required
    kind: TODO  # required
    namespace: TODO  # required
  to:  # required
  - group: ""  # required
    kind: TODO  # required
