---
apiVersion: v1  # first, required
kind: Secret  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app.kubernetes.io/name: TODO  # required
  annotations: {}
type: Opaque  # required
data: {}  # preferred
stringData: {}
