---
apiVersion: v1  # first, required
kind: ServiceAccount  # required
metadata:  # required
  name: TODO  # first, required
  namespace: TODO  # preferred
  labels:  # required
    app: TODO  # first
    app.kubernetes.io/name: TODO  # required
  annotations: {}
automountServiceAccountToken: TODO
imagePullSecrets:  # preferred
- name: TODO  # required
