---
apiVersion: admissionregistration.k8s.io/v1  # first, required
kind: ValidatingWebhookConfiguration  # required
metadata:  # required
  name: TODO  # first, required
  labels:  # required
    app.kubernetes.io/name: TODO  # first, required
  annotations: {}
webhooks:  # required
- name: TODO  # first, required
