---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cardano-playground
  namespace: argocd
  labels:
    app.kubernetes.io/name: cardano-playground
    app.kubernetes.io/part-of: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - ssh://git@github.com/input-output-hk/cardano-playground
  description: Cardano Playground infrastructure and applications
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
