---
# predictable-yaml: ignore-requireds
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "false"
  accounts.sre1: apiKey,login
  accounts.sre2: apiKey,login
  accounts.sre3: apiKey,login
  accounts.sre4: apiKey,login
  accounts.sre5: apiKey,login
