---
# predictable-yaml: ignore-requireds
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, sre1, role:admin
    g, sre2, role:admin
    g, sre3, role:admin
    g, sre4, role:admin
    g, sre5, role:admin

  # Default policy for unauthenticated users (deny all)
  policy.default: role:''
