---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../apps/argocd/base
- appProject.cardano-playground.yaml

components:
- ../../../components/spot-node-affinity

patches:
- path: configmap.argocd-cm.yaml
- path: configmap.argocd-rbac-cm.yaml

generators:
- ksops.generator.yaml
