# predictable-yaml: ignore
apiVersion: v1
kind: Secret
metadata:
    name: argocd-age-key
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    argocd-key.txt: ENC[AES256_GCM,data:c4jvFAAvMqR1vCaDQj+WoObqx7p573FrfAwr//CtFe+tiP6YfYHUiW6hD2SJrkEknXxFX1J45dLhtvmFOTtRPx4F792WIfFAKUc=,iv:Nkp64D1TfcrWHO7aga4WRbVo6zHsEMs3WERyMRkPtMI=,tag:wdFL2kAYU8vw4XK08hFl1w==,type:str]
sops:
    age:
        - recipient: age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOGE3T3dtYmsvc2VqcG51
            aG4yUCttUTcyb1pCNnZma0xvVXlkYVlSOG5RCktPZEVqMzk5RWNnMGg5MmQra1Na
            NXhTWEUrZThUS2lrdXJKbnlSbkpzUUkKLS0tIFJ6TUZlcGtKR0FLTWhrd2hUMmZs
            TmNkR2RaQ0hIYlpYOEFJQWdCSmxjTDAK1XM2On1qcn4p6SqDYZjhQaHiTt0Mwm3L
            nRI0lk8rUUjBupOtLOUQfV/M1YFf2xHoLyjoVUzwVmm+xpiB28EJpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wzx3jh874ejvwljl33qepnmsxt64wd7fl4zr4y5t5v25nvqyyqmqlpa6t3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOGZGQURlTWFRRy9Tdkw4
            cy9iL0Nibm5zeVF6Q2VBQ0cxVTJ3UlZCeDM0CkZybHdYTzV2cGI3ekpwY2tDdGEz
            Z01MZDFzSEY5dmJGRkNWV1U3YmdCUGsKLS0tIEQ5L2l3MkZablpEeWtMVzg1TWVR
            MmJwUkRwTnJCcjcrK0RUT1Z5eDg3aDAKooWgiNHrO0O2FWRkg6QpngrlJclzPv74
            uV8PU4pVaFiOyUa4hQKKvEO7Bjt3SYrZTC+xCd0aTPe5xawSBFgROQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:50:56Z"
    mac: ENC[AES256_GCM,data:K+c2/P/zh0m3yeNaNw71i34OCCoRmq01JJte99tv1ZHYHG4d9IZVE/JkwQCuDw+0zcsrgEiv8YEBmZ0w/p8/t+EwEP+REV6m7RaGcYgoQ/BMuWSdVWLbsgkfNJ1Re3tjCVbuVAU4K/NMg5dc2e6ZbcBUr0Nu1/iSqM4ly5xWb34=,iv:dwctiYoHLb5i8//T79T6BeWSOLgQuHQA0vXZeAUTBR8=,tag:UtYcNSDRVc5eRqg5Q0BD3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
