# predictable-yaml: ignore
apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    #ENC[AES256_GCM,data:pvtII9i1Mc/7Mc9mUsbrL1sM4IulOusLHo01sOikGyiFwEecYTA=,iv:UrKyF7ksqjL24b2uyfjJV867R3jdCOqo1a2y8SgXsRM=,tag:5rbfggRKLZqv0gMqYFuFEQ==,type:comment]
    #ENC[AES256_GCM,data:ituzgXp7XI8iD/dbyPIb0YfwD0OtFy75oCZ15Z0lV/8QZEWCGOLJC6OwcgpigQ==,iv:4uNXJWQS137V+gT2FmuhDK6h0x5itVUIfA6elLwIKDk=,tag:ttThrj0Y1qRqpCpkLo7TBg==,type:comment]
    #ENC[AES256_GCM,data:/YZKd+Qx2mBioGgeX5mNG3rGGxG1mTVu3cG9aCrYWK6YIV6FY2a7EMcNuJnvouuR353LmbZMsAjZiQdhMdhbTgtA4P46IQ==,iv:xw3ITqt23cimi9svDL8UwfuChXTLg3PRpqmmdGQgqZ8=,tag:54TnB1shRJh7qLtI43Xa4A==,type:comment]
    #ENC[AES256_GCM,data:51touaMX5u9UuoApheC/mPaIpoIorQ==,iv:Byz8AbZLeh32sWaGSIb9eVY3IeeF64MV+GEv3zwmPcM=,tag:KUy7pXmoWI0PPJ5FSEG7VQ==,type:comment]
    accounts.sre1.password: ENC[AES256_GCM,data:OIo2t7177+XYpGhQ4Mh53tgz8fyHBwoInICW08rbrM9QTTWkq1KvqHr7NPyd4BPeo9Yj1CEBLI+9/Gq4,iv:wTJASKlRTk7t/F6CGwXBm7hjvrFDE6UlW3XMefr04Hk=,tag:D3HxXjz5SeXeVpLRgHGWAQ==,type:str]
    #ENC[AES256_GCM,data:yBCCKvvmZSKhV9iEaiEy0E7YEAYNJA==,iv:ddTeRrebx8nxmhxcS1UBgqWv1J9LNu7XYzhUaJuwkcs=,tag:UxEsyD8zPH4hLA0errQgUw==,type:comment]
    accounts.sre2.password: ENC[AES256_GCM,data:/qU6wXrvCXL/2e1eF48hjk890HbkXJ8/Tvn6emyZgicIBLoZJ9LuSuZHVzDuPDIHajOg3bCHtnoQdXdZ,iv:atlW/WR0rgetbCcjevUNFxRBFZ7q8xxem5ajXUkXC5w=,tag:z9TSuQOjuZPKOO8vWwroxA==,type:str]
    #ENC[AES256_GCM,data:EeSpr5CFTQWR/L7AcTfUy7VkUtdG,iv:T6Hdr6gzq/9PN35s65XNpaNzVw3m/JDFamwNq12ktdM=,tag:+Rd85a9p+fQgZLqfKN982w==,type:comment]
    accounts.sre3.password: ENC[AES256_GCM,data:FKAieziRhEciB360B6lRIiKWwFDQ6pAonCzFRtd3r79gF1tnjC1mHNI/xb/fvdEmcjuMCGdbfkOCP23b,iv:AH2d0c3jigfL38aYK9dOIkW/1sV6mmC2Rg/hLUQAbcU=,tag:PvdX4clgBUOEGRukW3yaGg==,type:str]
    #ENC[AES256_GCM,data:wmv/qPjCbZuEETOn+Som/8GmEKo=,iv:TH6R5TF21/wy5hqsnAWNcfcMO+f9D77kfXMAayATgYg=,tag:/Uk+iuHBnow5TGwZ4VsKSA==,type:comment]
    accounts.sre4.password: ENC[AES256_GCM,data:N1PGok3ry26GMFwr43rwSRisCfp94dyfoerZL9i4yHEWXuQAa6UzQCxW0QXdgLA1VJ7tluhDAbV/ySVn,iv:gZGGl593zKpg6nnIKbRNndhSktNVXZLdTievPU2wY5A=,tag:xazrc9iCBk1vz3vUBhIckw==,type:str]
    #ENC[AES256_GCM,data:F3AQCz/ywrHACmlif0OBa+TrHss=,iv:+Sv+eqG1HAzsXXE+ggoAClL0Ji9/U1YzbfU4+zoG858=,tag:TDAVvI3ZPtDKseQi74SfWg==,type:comment]
    accounts.sre5.password: ENC[AES256_GCM,data:M9d4MtGN1a9C4PfUZwQRKFhK0n/QSz1nLyK8ZjgVJUhJH3Ue2SBoT6Ft2fGlB9FbGKJ0f04puwDSdiZC,iv:IGNMcpCpz2ywQ5YBDOU+17dn+1Roeo4xD9qOheHAKqM=,tag:RjDyPJ2qWrDgbGWdT7oSAQ==,type:str]
sops:
    age:
        - recipient: age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bW9LSm55YkJJdnBhM05s
            TUh4ZE8yeWloUEJVKzdzUmx3L2Z0elowbFJnClgxNHhNR2J3alVGTk05LzM4TnRI
            WHd4aW9ndHlCRmlVK0dGUXhybXBwTVEKLS0tIGpPK25nTW5yWXJhQlorSTEzV2tn
            OHVqVldQMGdRNEh4MUZMSGFHbHFXSlUKoEchyyQkM4lFuXUePZpFiQl4FS4tkqpZ
            aG104dQp+WAG4eX6kIbmylFZqEoJ2Xpy8yA0iYMBHMd1N1rtbmHK5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wzx3jh874ejvwljl33qepnmsxt64wd7fl4zr4y5t5v25nvqyyqmqlpa6t3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVCtiREkxcmJTZWtMRFRv
            RFVjYjhSQU9aRUNHdkNWdGFUQXNuMGlIeTNnCnJjYWNuaEFnd0xlMGNUQWJURTRX
            OEpiNVZEdHJWUkd5UnJtd2d2SWRLR2cKLS0tIHo2TkNlcFVPeXVETE5QQUc0b285
            MWhaL3V1SExjYmdGYktCb2sxSm8vZWsKkGzzCas7uJ7RDHK/jrQRuu8lhJLloJe1
            z0PoGFpTbBFige4Hl5h2zY5irnQ726+8aJMDUGbKw+kbxeAuNfZndg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:50:13Z"
    mac: ENC[AES256_GCM,data:X70cmVreyarzxnbNdX/G3/mYJi0ZLlltJ6S+b1dQZ0ImywYykEJYEIlV/0hGDF6pxqZO0zucVMEAm4YxUjlrHKhc/A1SWFgE8Zvs7QZQe4MGuEFLFP4XcUHWRrVGcy0SzyaXJcxqzg1/CZO/Jwk4YxxY0v2fcQwUGEWiENmkOZA=,iv:6OvFee4p29WEUicH64jg/lym9lRmRiM7j3QWKOfrM2U=,tag:0WkGXowtT8b2l6W0Eyyj9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
