---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aws-load-balancer-serving-cert
  namespace: aws-load-balancer-controller
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  dnsNames:
  - aws-load-balancer-webhook-service.aws-load-balancer-controller.svc
  - aws-load-balancer-webhook-service.aws-load-balancer-controller.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: aws-load-balancer-root-issuer
  secretName: aws-load-balancer-tls
  duration: 8760h0m0s
  renewBefore: 720h0m0s
