---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: aws-load-balancer-selfsigned-issuer
  namespace: aws-load-balancer-controller
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  selfSigned: {}
