---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager
        app: cert-manager
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/component: controller
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9402'
    spec:
      serviceAccountName: cert-manager
      containers:
      - name: cert-manager-controller
        image: 362174735783.dkr.ecr.eu-central-1.amazonaws.com/cert-manager-controller:v1.20.0
        imagePullPolicy: IfNotPresent
        args:
        - --v=2
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=kube-system
        - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.20.0
        - --max-concurrent-challenges=60
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http-metrics
          containerPort: 9402
          protocol: TCP
        - name: http-healthz
          containerPort: 9403
          protocol: TCP
        livenessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 8
          httpGet:
            port: http-healthz
            path: /livez
            scheme: HTTP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      enableServiceLinks: false
