---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cardano-book
  namespace: cardano-book
  labels:
    app.kubernetes.io/name: cardano-book
    app.kubernetes.io/part-of: cardano-book
spec:
  dnsNames:
  - CHANGEME
  - CHANGEME
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cardano-book-tls
