---
# predictable-yaml: ignore-requireds
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mdbook
  namespace: mdbook
spec:
  dnsNames:
  - book.k8s.iog.io
  - book-staging.k8s.iog.io
