---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
- name: mdbook-staging
  count: 0

resources:
- ../../../apps/mdbook/base

patches:
- path: deployment.mdbook-staging.yaml
- path: ingress.mdbook.yaml
