---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
- name: cardano-book-staging
  count: 0
- name: cardano-book-production  # temporarily scale down until ready for testing and cutover
  count: 0

resources:
- ../../../apps/cardano-book/base

patches:
- path: certificate.cardano-book.yaml
- path: deployment.cardano-book-staging.yaml
- path: httpRoute.cardano-book-production.yaml
- path: httpRoute.cardano-book-redirect.yaml
- path: httpRoute.cardano-book-staging.yaml
