{
 "title": "Cardano Node: Application metrics (New Tracing)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(cardano_node_metrics_blockNum_int,environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cardano Last Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.5,cardano_node_metrics_density_real{environment=\"$environment\"}) / 0.05",
     "legendFormat": "Density"
    }
   ]
  },
  {
   "title": "Cardano Last Block Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot leading share (% of slots led)",
   "type": "timeseries",
   "description": "Calculated at a 1 hr averaging window",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_nodeIsLeader_int{environment=\"$environment\"}[1h])/rate(cardano_node_metrics_slotNum_int{environment=\"$environment\"}[1h]) / 0.05",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(cardano_node_metrics_Forge_node_not_leader_counter{environment=\"$environment\"}[1h])/rate(cardano_node_metrics_slotNum_int{environment=\"$environment\"}[1h])) / 0.05",
     "legendFormat": "Total led slots"
    }
   ]
  },
  {
   "title": "Rejected blocks during the last day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum_over_time(abs((cardano_node_metrics_forgedSlotLast_int{environment=\"$environment\"} - cardano_node_metrics_forgedSlotLast_int {environment=\"$environment\"} == bool 0) - 1)[1d:])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cardano Last Block Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{environment=\"$environment\"}",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Missed slots rate (slots/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_slotsMissed_int{environment=\"$environment\"}[1h]) * 3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mempool Txs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_txsInMempool_int{environment=\"$environment\"}[30m]))",
     "legendFormat": "30 min average"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int{environment=\"$environment\"}[150s])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "quantile(0.5, cardano_node_metrics_blockfetchclient_blocksize_int{environment=\"$environment\"} / 90112)",
     "legendFormat": "last"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize_int{environment=\"$environment\"}[15m]) / 90112)",
     "legendFormat": "15 min average"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize_int{environment=\"$environment\"}[4h]) / 90112)",
     "legendFormat": "4h average"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize_int{environment=\"$environment\"}[24h]) / 90112)",
     "legendFormat": "24h average"
    },
    {
     "expr": "avg(avg_over_time(cardano_node_metrics_blockfetchclient_blocksize_int{environment=\"$environment\"}[7d]) / 90112)",
     "legendFormat": "7 days average"
    }
   ]
  },
  {
   "title": "Ping latency (ms)",
   "type": "timeseries",
   "description": "Cardano-node ping latency measured from localhost with cardano-cli ping",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_statsd_cardano_node_ping_latency_ms_gauge_value_average{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current KES Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.5,cardano_node_metrics_currentKESPeriod_int{environment=\"$environment\"})"
    }
   ]
  },
  {
   "title": "RTS GC CPU Utilization (2m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(irate(rts_gc_cpu_ms{environment=\"$environment\"}[2m]) + irate(rts_gc_mutator_cpu_ms{environment=\"$environment\"}[2m]) + irate(rts_gc_init_cpu_ms{environment=\"$environment\"}[2m])) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KES Periods Remaining",
   "type": "timeseries",
   "description": "KES periods remaining",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS)",
   "type": "timeseries",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used{environment=\"$environment\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}