---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../apps/external-dns/base

components:
- ../../../components/spot-node-affinity

patches:
- path: serviceAccount.external-dns.yaml
