---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cni-repair-role
  labels:
    app: istio-cni
    app.kubernetes.io/name: istio-cni
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    istio.io/rev: default
    release: istio
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
  - get
  - list
