---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    istio.io/rev: default
    release: istio
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      image:
        imageType: distroless
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    defaultProviders:
      metrics:
      - prometheus
    enablePrometheusMerge: true
    rootNamespace: istio-system
    serviceScopeConfigs:
    - scope: GLOBAL
      servicesSelector:
        matchExpressions:
        - key: istio.io/global
          operator: In
          values:
          - "true"
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
