---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-cni-config
  namespace: istio-system
  labels:
    app: istio-cni
    app.kubernetes.io/name: istio-cni
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    istio.io/rev: default
    release: istio
data:
  AMBIENT_DNS_CAPTURE: "true"
  AMBIENT_ENABLED: "true"
  AMBIENT_ENABLEMENT_SELECTOR: |-
    - podSelector:
        matchLabels:
          istio.io/dataplane-mode: ambient
    - namespaceSelector:
        matchLabels:
          istio.io/dataplane-mode: ambient
      podSelector:
        matchExpressions:
        - key: istio.io/dataplane-mode
          operator: NotIn
          values:
          - none
  AMBIENT_IPV6: "true"
  AMBIENT_RECONCILE_POD_RULES_ON_STARTUP: "true"
  CHAINED_CNI_PLUGIN: "true"
  CURRENT_AGENT_VERSION: 1.29.1
  ENABLE_AMBIENT_DETECTION_RETRY: "false"
  EXCLUDE_NAMESPACES: kube-system
  ISTIO_OWNED_CNI_CONFIG: "false"
  NATIVE_NFTABLES: "false"
  REPAIR_BROKEN_POD_LABEL_KEY: cni.istio.io/uninitialized
  REPAIR_BROKEN_POD_LABEL_VALUE: "true"
  REPAIR_DELETE_PODS: "false"
  REPAIR_ENABLED: "true"
  REPAIR_INIT_CONTAINER_NAME: istio-validation
  REPAIR_LABEL_PODS: "false"
  REPAIR_REPAIR_PODS: "true"
