---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: istio-cni-node
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-cni
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    istio.io/rev: default
    k8s-app: istio-cni-node
    release: istio
spec:
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: istio-cni
        app.kubernetes.io/instance: istio
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/version: 1.29.1
        helm.sh/chart: cni-1.29.1
        istio.io/dataplane-mode: none
        k8s-app: istio-cni-node
        sidecar.istio.io/inject: "false"
      annotations:
        container.apparmor.security.beta.kubernetes.io/install-cni: unconfined
        prometheus.io/path: /metrics
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-cni
      containers:
      - name: install-cni
        image: docker.io/istio/install-cni:1.29.1-distroless
        imagePullPolicy: IfNotPresent
        command:
        - install-cni
        args:
        - --log_output_level=info
        envFrom:
        - configMapRef:
            name: istio-cni-config
        env:
        - name: REPAIR_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REPAIR_RUN_AS_DAEMON
          value: "true"
        - name: REPAIR_SIDECAR_ANNOTATION
          value: sidecar.istio.io/status
        - name: ALLOW_SWITCH_TO_HOST_NS
          value: "true"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.cpu
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: metrics
          containerPort: 15014
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        readinessProbe:
          httpGet:
            port: 8000
            path: /readyz
        volumeMounts:
        - name: cni-bin-dir
          mountPath: /host/opt/cni/bin
        - name: cni-host-procfs
          mountPath: /host/proc
          readOnly: true
        - name: cni-net-dir
          mountPath: /host/etc/cni/net.d
        - name: cni-socket-dir
          mountPath: /var/run/istio-cni
        - name: cni-netns-dir
          mountPath: /host/var/run/netns
          mountPropagation: HostToContainer
        - name: cni-ztunnel-sock-dir
          mountPath: /var/run/ztunnel
        securityContext:
          privileged: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_PTRACE
            - SYS_ADMIN
            - DAC_OVERRIDE
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cni-bin-dir
        hostPath:
          path: /opt/cni/bin
      - name: cni-host-procfs
        hostPath:
          path: /proc
          type: Directory
      - name: cni-ztunnel-sock-dir
        hostPath:
          path: /var/run/ztunnel
          type: DirectoryOrCreate
      - name: cni-net-dir
        hostPath:
          path: /etc/cni/net.d
      - name: cni-socket-dir
        hostPath:
          path: /var/run/istio-cni
      - name: cni-netns-dir
        hostPath:
          path: /var/run/netns
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      priorityClassName: system-node-critical
