---
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    istio: pilot
    istio.io/rev: default
    release: istio
spec:
  type: ClusterIP
  selector:
    app: istiod
    app.kubernetes.io/name: istiod
    istio: pilot
  ports:
  - name: grpc-xds
    port: 15010
    protocol: TCP
  - name: https-dns
    port: 15012
    protocol: TCP
  - name: https-webhook
    port: 443
    targetPort: 15017
    protocol: TCP
  - name: http-monitoring
    port: 15014
    protocol: TCP
