---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ztunnel
  namespace: istio-system
  labels:
    app.kubernetes.io/name: ztunnel
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
