---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app: istiod
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    release: istio
