---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-cni
  namespace: istio-system
  labels:
    app: istio-cni
    app.kubernetes.io/name: istio-cni
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    istio.io/rev: default
    release: istio
