---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-reader-service-account
  namespace: istio-system
  labels:
    app: istio-reader
    app.kubernetes.io/name: istio-reader
    app.kubernetes.io/instance: istio
    app.kubernetes.io/part-of: istio
    release: istio
