---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterRole.external-dns.yaml
- clusterRoleBinding.external-dns-viewer.yaml
- deployment.external-dns.yaml
- namespace.external-dns.yaml
- serviceAccount.external-dns.yaml

transformers:
- labelTransformer.add-argocd-label.yaml
