{
	"data": "ENC[AES256_GCM,data:Z4rIttGXQlH49iLVW69oBKwHgRle98i7Ahi7VQBuMmxf09AtCrwTXxcIhB5+apTKovGwknnjRZ8zkGTYwlEWp/sutFHyx7XppKr/aXRYhQE+kvIoq2vaaRUTS0nyClIlZDJpGsxU1FPgpI1J2ObPcVKkiCvvfOkOtQs87D/bcaKi6x57T25/NUimMvGQkwW1nPexTYWR/X56HBq4qA5IZQJ0/2fpS6KdhVcsoSH2WVsY1Oc5pC13cIwl4om18yNhF0S51jwygoWb4eQbqd4XNTUchjoqDxS6fzJf2rfMQ1sXICtMTRTLKwZ5WU1wNWuCrDn9tBDDAr6HWFwfUDJJV7PmHPOYs4R4qp6M2olexADFQm9KH6ryUgzOajNUtcgLDlnMnl7c05CpyqMpyQyzcYN6fyKEYpySZlBYLewFQkSWE18zNfGLPZox6ieuL098Z0ODEjpye4ZrQ+cqW151U6qLQDi8skYrQ3Wu+cEUu1nrEKgu3Z8EmMtzYP93v3vuVzrHzqSJaaabbQ2s0AbQvYkh6s8Xj1CaBuEdoeiQRbY9n1ad3YamLIVnwl3HxzUInCYoqghnPw2YRzfU1eOEOZmVQ7ecvjHVkfFcIXmzyb6ei9LWhP0hIA+SYpfSq1rOh8JZgzfF+D7R3nNR77yM497jFJPdWTXNCqLAkG51Na5VmAL3F/cRAohkaWHY4JzM5OQqTQ5H1bj0qtp9mMq/UHt73Q==,iv:gEnF0RVGwH1I+af5hSxRRbgsTmO+4aKygS9nvbvSm4U=,tag:F0eGvKS6coMKnqAKEnjhig==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydGp4bmpQMU5iOXhZeVhw\naG0wdEdzSiszRXg1MVZySlovZm1ZV2RGT1dRCjNZVVV1V01Oc2NmYVhQTmVsOUVS\nTzJDdll2K3BFeWgrUmlRb3pKOTcrQWcKLS0tIGhCRHcxemYvN2ZQaWx5cU1XTEhW\nTXp5dWY0WFNpVkxTUitjcDdaUTJwMkEKDlBQhnYMEj8pTfY5bNMV/R3ojBMJmh4L\nkZA2ISLwHRfNNonFawP4qfcQ/KWPaxM4e7K2drOYNQy9hWbQzwXWOA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-25T22:35:34Z",
		"mac": "ENC[AES256_GCM,data:U9M4pt2C6yCN/JHS4bR7Cmwje+O6Z9scwDjiAUoPFTYYpq65JBggBksVb8uhToT6A7GOvwAPv63CjF4nlhLiOiDZr4ctbjb4UTvFtx6R0PK1okQ/cwsXjiZIF2pS5IM4/DNEto9pQLYvyLFRPTG8fGCewaZ1NlPVp2wuu1BrwlY=,iv:Fc6Po/n++C3PvYnFugbP5ugRwVqzYYypQForhEYEZ6M=,tag:2xzW9XPmKdp47M0QJXAOQQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
