---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment|StatefulSet
  patch: |-
    - op: add
      path: /spec/template/spec/affinity
      value:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: capacity-type
                operator: In
                values:
                - spot
    - op: add
      path: /spec/template/spec/tolerations
      value:
      - key: spot
        operator: Equal
        value: "true"
        effect: NoSchedule
