---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authorizationPolicy.mdbook.yaml
- certificate.mdbook.yaml
- deployment.mdbook-production.yaml
- deployment.mdbook-staging.yaml
- httpRoute.mdbook-production.yaml
- httpRoute.mdbook-redirect.yaml
- httpRoute.mdbook-staging.yaml
- referenceGrant.envoy-gateway.yaml
- service.mdbook-production.yaml
- service.mdbook-staging.yaml

transformers:
- labelTransformer.add-argocd-label.yaml
