# predictable-yaml: ignore
apiVersion: v1
kind: Secret
metadata:
    name: argocd-age-key
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-age-key
        app.kubernetes.io/part-of: argocd
type: Opaque
sops:
    age:
        - recipient: age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MGRQYUpsbFdnR1BrMmRD
            bnhpREF4N1l6YWZWaUMyUmRjN0ZreTVHZjBZCm5sS0JZa1hhZVU5UGcvRWRRYVNG
            Z2d6ZzBoRGtqMXg5M3FNdDlJWUdENVEKLS0tIEtMcjllTHJ6ajlDTFFBWklXMFRw
            SUhadjlmSUhBT25kU05MZ1BlN0toZW8KFRw4PfDqr4cXNVqvjK+IfK/gvj5uY8q5
            FrMppdm6nPDDQslvGNly6K919Ho7Ky5bqAMc1mTkwN9Kr1lbW7+zbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wzx3jh874ejvwljl33qepnmsxt64wd7fl4zr4y5t5v25nvqyyqmqlpa6t3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UnNDMzVENVh5YVBOS1U5
            KzZkNS9pVzh6S255ZnM1eVJqUzVZcFgrekdFClk3cG5TOFRnOTI3MmU0cjRNNFlv
            Q29sTVdZVDVMSlU1M3V4ZjU4aTVIZ2sKLS0tIHQvRlVuY0dPUFk0a2NvTS9qOU9j
            OEtvcHFoTmRMcFRuN29oZlZxZFJJckEKeitzX/n/IJl76DAYVWJr6xBbZjJs/Vrd
            +yFhZS/CSy3uKHReDbrjOQFpR1npNvub5XHF++rVl2Ft3h7TvI4prw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:49:37Z"
    mac: ENC[AES256_GCM,data:0q4PPISh7On8yyhGi6Cp8nGvX6yT5YodCb/21aTogIeegnNBZkiQ0vSzCWONgKxrpOmurBnQSaIMwaKvbaPCXW2+wxZCA3b/8uRu8D8qJ0Av6aQ/F/hiSE6YFyP9H5tGoYNw+Cx1FgYEjk+4VtiQ51hI1QJq7k03Z/NwAftw8m8=,iv:+ZsvsDoMmpU6OHrFDbFVS7ISGVmdI4tDrXbAUpF0qoI=,tag:Tosf0bMW8Ds0BAWmyi9zAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
