# predictable-yaml: ignore
apiVersion: v1
kind: Secret
metadata:
    # argocd chose this stupid name with the kind in it, we can't change it
    name: argocd-secret
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
type: Opaque
sops:
    age:
        - recipient: age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObGwxdFJVb2NEakdUWWYz
            bkVvUjZyTEphQlNEMXM2US9LOHZXdWhwSTFJCll5OFk0VXhtTGtlR2l6RmcvSHRh
            a0EyZ1N0YU5RWjRhb242SHFLYlpBUFkKLS0tIGtwWldCaFVxaE1tWTlYSkFHTlRN
            WHlxZkJSOE5rVnRrZFhiTWNQckpIeFEKgaoPq0nRLG3GJbLbRXIssePb3xO1MpZM
            q/h1xWEJeXFVcH8hFeZYnTQsUKHN3nWh2oU7GlYJ+ekZzkFKyySU2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wzx3jh874ejvwljl33qepnmsxt64wd7fl4zr4y5t5v25nvqyyqmqlpa6t3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdzd6em5LUWErcmgrUk5r
            OXFMRnJIdjdyODN1b3QvRDAvcDJiNlcwUkh3ClBRVjR6VXlkbS9YVVA4Nkl6ayt0
            WUs1UHVaeFpIYS9MdU4wZ0pMWEVFOUEKLS0tIGMvdWtISko1S29iZmpJQllJYkto
            RXVJSEx0WDlxL2NwQzViVEwxOHJjWEEKHMte74AJz5BOl1dZvn+Ee5o3X6AlKutT
            00klPgx+SlfO3prd4ySXR6AcdxboITZsf0ARF1XepP1LzaPbtnujhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T18:49:56Z"
    mac: ENC[AES256_GCM,data:gXoukcUkMIwPDkv4N0SBMjmGjOiOU5jgLl/0jGX39Zz0KgfGUfiON2w9EWNWArL/OwTTGsWZFrriUSS1GPM6/nScGWFb8KH9lNGWrsBbD+uZCUoko/gvIWp7MK6+sIxUY6blgBBHOZwpHNXYhwiTDHKEM1FgRllkCuxbXYSXikQ=,iv:PPWSqS6nRZZp06UTaL3oYIpVIwJ/RcxfmF+29bjc09U=,tag:fPCbEl/hapXmr4c3Epf77g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
