apiVersion: v1
kind: Secret
metadata:
    # argocd chose this stupid name with the kind in it, we can't change it
    name: argocd-secret
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
type: Opaque
sops:
    age:
        - recipient: age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOG5hNmlKU2J0b0ZtSEFY
            V2J4VVRMSDBhOEErYVBlUDZsdG5CaUxyNmlzCkxqeG5PWnpNZ3dJNTNFdFprYVY0
            dS8zdnpidnBHSktwM3FmU1BGV3NuRkUKLS0tIEJKNFQ2dGF6Y3NGQWZTWkZyVita
            RVNyVTE0NVdKbGRuMis2ZS94S3hURGsKQmy45tNAUor1JeWINMuHy4kh8vPJ4aCP
            BUgRFqSHw/jx/xk+ojvlCfkymqv0Ev/j6t0yoRCJ3xDq52ZNGUT8iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T00:29:51Z"
    mac: ENC[AES256_GCM,data:8NaZYe501RDRl/5Lxbngu4TpleIvjWkZS2+RMr9c0iB5uFFYbygEF7Y+lniRoCrCHG6779poPTsh35JnzbrcVCXTOcVPDKzv7KcFHQeJktk5lMxeH6j+dAUo++PfmUY7awkIFJC984hK3xF5T5q+LJE2x7vrbha6RpCjYNBs0O8=,iv:PuRUBjmOW2hfTBjTsBcjPrGUA5rQ/tHRYieu9ZAqIvU=,tag:GsR69J9IADkQVEZ52Abc6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
