---
apiVersion: v1
kind: Service
metadata:
  name: argocd-redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-redis
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
