---
apiVersion: v1
kind: Service
metadata:
  name: argocd-applicationset-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-applicationset-controller
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-applicationset-controller
  ports:
  - name: webhook
    port: 7000
    targetPort: webhook
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
