---
apiVersion: v1
kind: Service
metadata:
  name: argocd-dex-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-dex-server
  ports:
  - name: http
    port: 5556
    targetPort: 5556
    protocol: TCP
    appProtocol: TCP
  - name: grpc
    port: 5557
    targetPort: 5557
    protocol: TCP
  - name: metrics
    port: 5558
    targetPort: 5558
    protocol: TCP
