---
apiVersion: v1
kind: Service
metadata:
  name: argocd-notifications-controller-metrics
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-controller-metrics
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-notifications-controller
  ports:
  - name: metrics
    port: 9001
    targetPort: 9001
    protocol: TCP
