{
	"data": "ENC[AES256_GCM,data:RLqPLhsitsAnjOwzRbul+dIpl2/EfsLbcuKMU31eqetDs25EYF1FEhCjCvncEsu7iLG78KtCCstE6CR5u8AOOck5CZDk3f7GptSi+4thZXV0nSo3WFzmLEPAugO7k+huL5+h0wtJZkhkKppTr+5WU7wShrG5HUt5xltcKeO2mbWN/yQi9Bec5Wtws3PZi9j5ua+PKrYvW6Q3NN6w96Zz6bkU/zAcy/XmLzSXqnXlBGWkGu9bt/i5ZMQ3zvBYDZp4r8RRMCOHHssnbfHH4enO5D8mheZ4jv6ZkjkQgc9zBIiJ1cLPfKfpJinbxf951ZRhM7s1fl50OYs+0fYFAl80Uk+5DsQQO2I9TQDltMH1s8AsCBhJmaWcEdm68c+p6eXQRczbYp1ObC9B1t+AOyh579g/ZE7fvti54AoX7rwyIvjOgucW//40qOC7yXiJaD01wVhJE0Nap0oPCeWZ/sbkj+FaRAzIHE7u5tJWgA2aEW/op2KDBzdDSwTyoPT8l8/dMcJwsW5F+qM6G9VGVmxhI2ADSMRhztDZUQI4h1dvgg05cN0pQ7wFsdbCAT/1QJ9pPH5HLy0g5/yhhyihUa+o62mcnzW6ymmIQxfGXWgH57l+YndIbP2dEAQhsMIj8qzxUZeanaHE65cSYoCLSe4ixAu4C1SBjvTbk80niMGJDiH7fJ5E6UFLLuzm27gzaqGIcrzU/9zDmdqGUjq7rnt5avLO8g==,iv:bE04CaIw8lJVSpkKgERtAKGy0lmC8j/xT2Rgw2Yl5jg=,tag:xbhQvIHZya4+Kv01ks8Ggg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aTFmbFZqdXU3UzNwMFU2\nSXdYVHdXTkc2MWliZTRmaXJ2MDJlZERiK0FnCi9JNm9RYlU4WmxYbDYrYm45bUo0\naHdGTlY0bkEwdzZTMENTZzBEWldkZjgKLS0tIFh3RnRaVFZHaHU2K2hSeGdMelRh\nUVVMSUhSQjhxbVFFdmx0SWt5by9XS2sKVgg2H/BWPzsNdYJfoRpoTia6O8LJI0FD\n6M8DJBYqO6eVonI6zP84mCnbk3XzWYnyR3NXAsz0Vs14M4ic3IkE6Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-07-17T22:05:43Z",
		"mac": "ENC[AES256_GCM,data:xAJU0wCgFzn7ZhVH50ij8jAFyoZG7da2VqiIvKU13xx/+wPTAAODptdQTx4+IhtM7m+SKfkYW5slIgS4zOmyp670YNy5F0jaRodTAHBXMYREaCZ1/UUmkFcJE0jyoSLSQ7NNo3P5LFnM1Ql+Xih4+O0weme5DCL9RTyYtPaio34=,iv:Rd133MwbyR20k9HXFpIv0G0wcQEeID2cjJTHVMXUkv8=,tag:dWHC+FQaH61qjmSxQyfhIQ==,type:str]",
		"unencrypted_suffix": "_unencrypted",
		"version": "3.10.2"
	}
}
